version: '3.9'
services:
  flask:
    image: carspricepredictionproject
    build: 
        context: .
        dockerfile: dash.Dockerfile
    volumes:
      - ./.vscode-server:/root/.vscode-server
      - 
